# Generated by Django 4.2.4 on 2023-09-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_date', models.DateTimeField(auto_now_add=True, verbose_name='Время рассылки')),
                ('once_a_day', models.BooleanField(default=True, verbose_name='Периодичность: раз в день')),
                ('once_a_week', models.BooleanField(default=False, verbose_name='Периодичность: раз в неделю')),
                ('once_a_month', models.BooleanField(default=False, verbose_name='Периодичность: раз в  месяц')),
                ('status', models.CharField(max_length=100, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Тело письма')),
                ('mailing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус попытки')),
                ('mailing', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
