# Generated by Django 4.2.4 on 2023-09-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_client_mailing_list_mailingmassage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активация рассылки'),
        ),
    ]
