# Generated by Django 4.2.4 on 2023-09-03 16:37

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit
import mailing.views


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mailing.client')),
            ],
            bases=('mailing.client',),
        ),
        migrations.CreateModel(
            name='MailingCreateView',
            fields=[
                ('clients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mailing.clients')),
            ],
            bases=(mailing.views.DispatchMixin, django.contrib.auth.mixins.LoginRequiredMixin, 'mailing.clients', django.views.generic.edit.CreateView),
        ),
        migrations.CreateModel(
            name='MailingUpdateView',
            fields=[
                ('clients_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mailing.clients')),
            ],
            bases=(mailing.views.DispatchMixin, django.contrib.auth.mixins.LoginRequiredMixin, 'mailing.clients', django.views.generic.edit.UpdateView),
        ),
    ]
