# Generated by Django 4.2.4 on 2023-09-03 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0004_clients_mailingcreateview_mailingupdateview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglogs',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='mailingmassage',
            name='mailing',
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mailing.client'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='logs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailinglogs'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingmassage'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='mailings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing'),
        ),
        migrations.AddField(
            model_name='mailingmassage',
            name='mailings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Активация рассылки'),
        ),
    ]
