# Generated by Django 4.2.4 on 2023-09-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_mailinglogs_mailing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglogs',
            old_name='mailings',
            new_name='mailing',
        ),
        migrations.RenameField(
            model_name='mailingmassage',
            old_name='mailings',
            new_name='mailing',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='owner',
        ),
    ]
