# Generated by Django 4.2.4 on 2023-09-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_options_remove_mailinglogs_mailing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingmassage',
            name='owner',
        ),
    ]
