# Generated by Django 4.2.4 on 2023-09-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_remove_mailingmassage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='owner',
        ),
    ]
