# Generated by Django 4.2.4 on 2023-09-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_client_owner_mailingmassage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_date',
            field=models.DateTimeField(verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='once_a_day',
            field=models.BooleanField(default=False, verbose_name='Периодичность: раз в день'),
        ),
    ]
