# Generated by Django 4.2.4 on 2023-09-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailing_mailing_date_alter_mailing_once_a_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='last_mailing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней попытки'),
        ),
    ]
